### ISSUE TITLE
Installation Process/Dependencies

### ISSUE THREAD

**Issue by nrioux** [XSnow/bowtie_coq#1]
Hey I just wanted to add some notes I had on the install process that weren't in the readme.

- metalib is required. I installed via opam, but to do this I first had to add https://coq.inria.fr/opam/extra-dev as a repository to opam.
- The most recent version of metalib requires Coq 8.15.
- lngen is also required. I couldn't find a way to install this via a package manager. Looks like you have to do it manually from source: https://github.com/plclub/lngen (Doing this and getting the executable on my PATH was non-trivial but maybe I missed an easier way to do things)

**Comment by XSnow** [comment]
Thanks for the notes!
I were a bit sloppy in this repo. But maybe you can take a look at the other repo I have and see if the instruction in that readme is helpful? I will update this readme later.
https://github.com/xsnow/tamingmerge

**Comment by XSnow** [comment]
I am closing the issue as the readme is updated.
Instructions about metalib and lngen can be found in "Prerequisites for building from scratch".
Although the latest version of metalib (be0f81c) requires Coq 8.15, it is actually compatible with Coq 8.14.
